version: "3.0"
services:
  frontend:
    build:
      context: frontend
    ports:
      - 8080:3000
    tty: true
    volumes:
      - ./frontend/ws:/home/node/ws
      - /home/node/ws/node_modules
  backend:
    build:
      context: backend
    ports:
      - 8081:8080
    tty: true
    volumes:
      - ./backend/ws:/home/user/ws
