version: "3.0"
services:
    nginx:
      image: nginx:latest
      container_name: nginx
      restart: always
      ports:
        - "443:443"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/https/https.crt:/etc/nginx/conf.d/https.crt
        - ./nginx/https/https.key:/etc/nginx/conf.d/https.key
      extra_hosts:
      - "host.docker.internal:host-gateway"
      networks:
        - network
    frontend:
        restart: always
        build:
            context: frontend
        tty: true
        volumes:
            - ./frontend/workspace:/home/node/workspace
            - /home/node/workspace/node_modules
        entrypoint: "npm start"
        networks:
            - network
        depends_on:
            - nginx
    backend:
        restart: always
        build:
          context: backend
        tty: true
        volumes:
            - ./backend/workspace:/home/user/workspace
        networks:
            - network
        entrypoint: "go run main"
        depends_on:
            - db
            - nginx
    db:
        restart: always
        container_name: db
        build:
            context: db
        tty: true
        ports:
            - 3306:3306
        volumes:
            - ./db/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
            - ./db/config:/etc/mysql/conf.d/:ro
        networks:
            - network
    torch:
        restart: always
        container_name: torch
        build:
            context: torch
        tty: true
        volumes:
            - ./torch/workspace:/home/user/workspace
        networks:
            - network
        entrypoint: "python3 main.py"
    grafana:
        image: grafana/grafana
        restart: always
        container_name: grafana
        volumes:
            - ./grafana/grafana:/var/lib/grafana
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
        networks:
            - network
        user: "$PID:$GID"
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./prometheus:/etc/prometheus
        command: "--config.file=/etc/prometheus/prometheus.yml"
        restart: always
        networks:
            - network
networks:
    network:
        external: true
