version: "3.0"
services:
  frontend:
    build:
      context: frontend
    ports:
      - 8080:3000
    tty: true
    volumes:
      - ./frontend/ws:/home/node/ws
  backend:
    build:
      context: backend
    ports:
      - 8081:8080
    tty: true
    volumes:
      - ./backend/ws:/home/user/ws
  torch:
    build:
      context: torch
    ports:
      - 8082:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    volumes:
      - ./torch/ws:/home/user/ws
