version: "3.0"
services:
    frontend:
        build:
            context: frontend
        ports:
            - 8080:3000
        tty: true
        volumes:
            - ./frontend/workspace:/home/node/workspace
            - /home/node/workspace/node_modules
        entrypoint: "npm start"
    backend:
        build:
          context: backend
        ports:
            - 8081:3000
        tty: true
        volumes:
            - ./backend/workspace:/home/user/workspace
        networks:
            - network
        entrypoint: "go run main"
        depends_on:
            - db
    db:
        container_name: db
        environment:
            BIND-ADDRESS: 0.0.0.0
        build:
            context: db
        tty: true
        volumes:
            - ./db/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
            - ./db/config:/etc/mysql/conf.d/:ro
        networks:
            - network
    torch:
        container_name: torch
        build:
            context: torch
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        tty: true
        volumes:
            - ./torch/workspace:/home/user/workspace
        networks:
            - network
        entrypoint: "python3 main.py"
networks:
    network:
        external: true
